apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/himanshutailorpaysecure/python-gitops.git'
    targetRevision: HEAD
    path: my-chart # Path to where 'Chart.yaml' is in your repo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
